### ISSUE TITLE
Decouple payer in allow_list guard

### ISSUE THREAD

**Issue by 0x6c23** [metaplex-foundation/mpl-candy-guard#61]
The current implementation of the allowList guard uses the payer for validating against the merkle tree by default:

https://github.com/metaplex-foundation/mpl-candy-guard/blob/3e4a8786dfeccea9d1e03ac145964f1f5840c024/program/src/guards/allow_list.rs#L79

Meaning, when calling the ``proof`` guard route and when minting with an active allow list the payer must be the one on the allow list. Enforcing the feePayer to be allow listed creates some pain points in our flow, mainly being:  

1. It is not possible anymore to use an empty wallet for minting with an active allow list, forcing us to pre-fund empty custodial wallets
2. Complicating the minting flow by making us use hacky workarounds such as transferring SOL since we can't specify a treasury as feePayer anymore

Being able to specify a feePayer which is not on the allow list and instead validating another entity such as the mint authority would clean up the flow for our use-case immensely and elevate failure points, allowing us to more easily integrate clients asking for this feature.

**Comment by febo** [comment]
This is a good suggestion. We will include a separate `nft_owner` from the `payer`, so the `payer` is only used for fee payment and all the access validation is done on the `nft_owner`.

**Comment by febo** [comment]
@0x6c23 PR #72 will add support for this.
